### PR TITLE
Add Chrome as an alternative target for the Selenium webdriver

### PR DESCRIPTION
**Pull request by Rypac**
A few of the changes:

* Add Chrome as an alternative target for the Selenium webdriver
* Add `chromedriver` and `geckodriver` as NPM dependencies
* Remove scripts which install `geckodriver` and Firefox
* Add Selenium drivers to path when executing `cucumber_browser_runner`
* Migrate to Yarn
* Upgrade to the latest Node LTS (v6.10.3)
* Clean up README

### CODE REVIEW

**Comment by dueckes** [comment]
Hey Ryan, are we dropping Firefox support here?
Why not support both Firefox and Chrome?

**Comment by Rypac** [comment]
@dueckes No there's still support for Firefox and it's actually the default. I just added Geckodriver as an NPM dependency so there is no need to install it manually.

The driver is selected using the `SELENIUM_DRIVER` environment variable.

**Comment by andykingking** [comment]
👍  BUMP

**I need this!**

@dueckes

**Comment by dueckes** [comment]
Now merged with changes and released!

**Comment by andykingking** [comment]
Woo! Thanks @dueckes and @Rypac

**Pull request closed without merging**
